config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :articles, path: "blog/:username/" do
    resources :comments, :only => [:create, :destroy] do
      member do
        post :report
      end
    end
  end

  resource :user, :only => [:edit, :update]

  get 'change_locale/:locale' => "welcome#change_locale", :as => "change_locale"

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)

    can :index, Article

    can :show, Article

     can [:new, :create, :edit, :update, :destroy], Article do |article|
      article.user == current_user
    end

    can :report, Comment do |comment|
      !current_user.nil? && comment.user != current_user
    end


    can :create, Comment do
      !current_user.nil?
    end
    can :destroy, Comment do |comment|
      comment.user == current_user || comment.article.user == current_user
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_validation :init_username
  validates :username, presence: true, uniqueness: true, :format =>{ with: /\A[a-zA-Z]*\z/,}

  has_many :articles, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  protected

  def init_username
    self.username = ('a'..'z').to_a.shuffle[0,8].join if self.username.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_featured_blogs
  before_action :set_locale

  protected

  #returns blogs that have at least one articles
  def set_featured_blogs
    # joins uses an inner join by default so using User.joins(:articles)
    # will in effect only return users that have an associated articls.
    @featured_users = User.joins(:articles).uniq
  end

  def set_locale
    # several available options
    # pass the locale
    #  * via a parameter
    #  * via dynamic segment in routes
    #  * depending on the domain name
    # here we use the session to store the locale
    I18n.locale = session[:locale] || I18n.default_locale
  end

  def i18n_model_name(model)
    model.try(:class).try(:model_name).try(:human).try(:downcase)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_user
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /blog/:username
  def index
    authorize! :index, Article
    @articles = @user.articles
  end

  # GET  /blog/:username/:id
  def show
    authorize! :show, @article
    @comments = @article.comments.order(:created_at => "asc")
    @comment = @article.comments.build
  end

  # GET /blog/:username/new
  def new
    @article = @user.articles.build
    authorize! :new, @article
  end

  # GET /blog/:username/:id/edit
  def edit
    authorize! :edit, @article
  end

  # POST /blog/:username
  def create
    @article = @user.articles.build(article_params)
    authorize! :create, @article

    if @article.save
      redirect_to article_path(@user.username, @article),
                  notice: t('flash_messages.created', :resource_name => i18n_model_name(@article))
    else
      render :new
    end
  end

  # PATCH/PUT /blog/:username/:id
  def update
    authorize! :update, @article
    if @article.update(article_params)
      redirect_to article_path(@user.username, @article),
                  notice: t('flash_messages.updated', :resource_name => i18n_model_name(@article))
    else
      render :edit
    end
  end

  # DELETE /blog/:username/:id
  def destroy
    authorize! :destroy, @article
    @article.destroy
    redirect_to articles_url(@user.username),
                notice: t('flash_messages.destroyed', :resource_name => i18n_model_name(@article))
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = @user.articles.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def set_user
    @user = User.find_by_username(params[:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_article
  before_action :set_comment, only: [:report, :destroy]


  # POST /blog/:username/:article_id/comments
  def create
    @comment = @article.comments.build(comment_params.merge(:user => current_user))
    authorize! :create, @comment
    if @comment.save
      redirect_to article_path(@user.username, @article),
                  notice: t('flash_messages.created', :resource_name => i18n_model_name(@comment))
    else
      render 'new'
    end
  end

  # POST /blog/:username/:article_id/comments/1/report
  def report
    authorize! :report, @comment
    @comment.report_count += 1
    @comment.save
    redirect_to article_path(@user.username, @article),
                notice: t('flash_messages.reported')
  end

  # DELETE /blog/:username/:article_id/comments/1
  def destroy
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to article_path(@user.username, @article),
                notice: t('flash_messages.destroyed', :resource_name => i18n_model_name(@comment))
  end

  private
  def set_article
    @article =  @user.articles.find(params[:article_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = @article.comments.find(params[:id]);
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user
    @user = User.find_by_username(params[:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  # GET  /user/edit
  def edit
    @user = current_user
  end

  # PATCH/PUT /user/
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path,
                  notice: t('flash_messages.updated', :resource_name => i18n_model_name(@user))
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.order(created_at: :desc).limit(10)
  end

  def change_locale
    session[:locale] = if params[:locale].in? ['en', 'fr']
                         params[:locale].to_sym
                       else
                         nil
                       end
    # not suitable for production but useful for this course
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<h1><%= link_to_unless_current(article.title, article_path(article.user.username, article)) %></h1>

<%= simple_format(article.text) %>
<%= t 'published_by' %> <%= link_to article.user.username, articles_path(article.user.username)%>

<% if can? :edit, article %>
  <%= link_to t('edit'), edit_article_path(article.user.username, article) %>
<% end %>

<% if can? :destroy, article %>
<%= link_to t('destroy'), article_path(article.user.username, article), method: :delete, data: { confirm: t('are_you_sure') } %>
<% end %>

app/views/articles/_form.html.erb
<%
   if @article.persisted?
     # article exists => send to update
     url = article_path(@user.username, @article)
     method = :put
   else
     # article is new => send to create
     url = articles_path(@user.username)
     method = :post
   end
%>
<%= form_for @article, :url => url, :method => method do |f| %>
  <%= render "shared/validation_errors", :model => @article %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to t('show'), article_path(@user.username, @article)%> |
<%= link_to t('back'), articles_path(@user.username) %>

app/views/articles/index.html.erb
<h1><%=@user.username%></h1>

<% if can? :new, Article.new(user: @user) %>
  <%= link_to t('new_article'), new_article_path(@user.username) %>
<% end %>

<% @articles.each do |article| %>
  <div class="article">
    <%= render "articles/article" , :article => article %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path(@user.username) %>

app/views/articles/show.html.erb
<div class="article">
  <%= render "articles/article" , :article => @article %>
  <%= render 'comments/index', :comments => @comments, :comment => @comment%>
</div>

app/views/comments/_comment.html.erb
<%= simple_format comment.text %>
<%=t 'published_by'%> <%= link_to comment.user.username, articles_path(comment.user.username)%>

<%if can? :destroy , comment %>
  <%= link_to t('destroy'),
              article_comment_path(comment.article.user.username, comment.article, comment),
              method: :delete,
              data: { confirm: t('are_you_sure') } %>
<% end %>

<%if can? :report , comment %>
  <%= link_to t('report'),
              report_article_comment_path(comment.article.user.username,   comment.article, comment),
              :method => :post %>
<% end %>

<% if comment.report_count > 0%>
  (<%=t 'number_of_reports'%>: <%= comment.report_count %> )
<% end %>

app/views/comments/_form.html.erb
<% if can? :create, comment %>
  <%= form_for comment, url: article_comments_path(@user.username, @article, comment)  do |f| %>
    <%= render "shared/validation_errors", :model => comment %>

    <div class="field">
      <%= f.text_area :text %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/comments/_index.html.erb
<div class="comments" %>
  <% comments.each do |comment| %>
    <%= render 'comments/comment', :comment => comment %>
  <% end %>
  <%= render 'comments/form', :comment => comment %>
</div>

app/views/comments/edit.html.erb
<%= render 'form', :comment => @comment %>

app/views/comments/new.html.erb
<%= render 'form', :comment => @comment %>

app/views/comments/show.html.erb
<%=render 'comments/comment', :comment => @comment %>

app/views/layouts/_flash_messages.html.erb
<% if !notice.blank? %>
  <div class="notice ">
    <%= notice %>
  </div>
<% end %>

<% if !alert.blank? %>
  <div class="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="header">
  <%= link_to t('home'), root_path %>

  <% if current_user %>
    <%= link_to t('my_blog', :username => current_user.username), articles_path(current_user.username) %>
    <%=link_to t('settings'), edit_user_path %>
    <%=link_to t('devise.views.common.log_out'), destroy_user_session_path, :method => :delete %>
  <% else %>
    <%=link_to t('devise.views.common.log_in'), new_user_session_path%>
    <%=link_to t('devise.views.common.sign_up'), new_user_registration_path %>
  <% end %>

  <div class="pull-right" >
    <%= link_to_if(I18n.locale != :en, "en", change_locale_path("en")) %> |
    <%= link_to_if(I18n.locale != :fr, "fr", change_locale_path("fr")) %>
  </div>
</div>

<div class="featured-blogs">
  <%=t('featured_blogs') %> :
  <% @featured_users.each do |user| %>
      <%= link_to user.username, articles_path(user.username) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogG4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header"%>
<%= render "layouts/flash_messages"%>

<%= yield %>

</body>
</html>

app/views/shared/_validation_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%=I18n.t("errors.messages.not_saved",
                  count: model.errors.count,
                  resource: model.class.model_name.human.downcase)%></h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<%end%>

app/views/users/edit.html.erb
<h1><%= t('settings')%></h1>
<%= form_for(@user, :url => user_path, :method => :put) do |f| %>
  <%= render "shared/validation_errors", :model => @user %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>

  </div>

  <%= f.submit t('save') %>
<% end %>

app/views/welcome/index.html.erb
<h1>Recent articles</h1>

<% @articles.each do |article| %>
  <div class="article">
    <%= render "articles/article" , :article => article %>
  </div>
<% end %>